[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["database"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "database"
  org = "hasitha"
  version = "3.1.1"

